trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: azure-flask-app
  acrName: acrandersondevops123
  resourceGroup: rg-devops-lab

steps:

# Login Azure CLI MANUAL (device code)
- script: |
    az login --use-device-code
  displayName: Azure Login

# Login ACR
- script: |
    az acr login --name $(acrName)
  displayName: Login ACR

# Build
- script: |
    docker build -t $(imageName):$(Build.BuildId) .
  displayName: Build

# Tag + Push
- script: |
    docker tag $(imageName):$(Build.BuildId) $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
    docker push $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
  displayName: Push

# Deploy
- script: |
    az containerapp update \
      --name devops \
      --resource-group $(resourceGroup) \
      --image $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
  displayName: Deploy