trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: azure-flask-app
  acrName: acrandersondevops123
  resourceGroup: rg-devops-lab
  containerApp: azure-flask-app

steps:

# 1. Build Docker image
- script: |
    docker build -t $(imageName):$(Build.BuildId) .
  displayName: Build Docker Image

# 2. Login no Azure
- task: AzureCLI@2
  displayName: Azure Login + ACR Login
  inputs:
    azureSubscription: azure-connection
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(acrName)

# 3. Tag image
- script: |
    docker tag $(imageName):$(Build.BuildId) \
    $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
  displayName: Tag Image

# 4. Push no ACR
- script: |
    docker push $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
  displayName: Push to ACR

# 5. Deploy no Container Apps
- task: AzureCLI@2
  displayName: Deploy Container App
  inputs:
    azureSubscription: azure-connection
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az containerapp update \
        --name $(containerApp) \
        --resource-group $(resourceGroup) \
        --image $(acrName).azurecr.io/$(imageName):$(Build.BuildId)